added traing data upload, model training config+model training script + metrics check + model upload to model registry

diff --git a/.github/workflows/app-dev.yml b/.github/workflows/app-dev.yml
--- a/.github/workflows/app-dev.yml
+++ b/.github/workflows/app-dev.yml
@@ -172,23 +172,20 @@ jobs:
                 --workspace-name "$ml_workspace"
                 
                 # job result
-                # r2_adj=$(az ml job show --name "$run_id" -g "$rg_name" -w "$ml_workspace" --query "tags.r2_adj" -o tsv)
-                # echo "$r2_adj"
+                r2_adj=$(az ml job show --name "$run_id" -g "$rg_name" -w "$ml_workspace" --query "tags.r2_adj" -o tsv)
+                echo "$r2_adj"
 
-                # if [ "$(echo "$r2_adj < 0.99" | bc -l)" -eq 1 ]; then
-                # echo "Validation Failed: R2_ADJ is too low ($r2_adj)"
-                # exit 1
-                # fi
+                if [ "$(echo "$r2_adj < 0.99" | bc -l)" -eq 1 ]; then
+                echo "Validation Failed: R2_ADJ is too low ($r2_adj)"
+                 exit 1
+                fi
 
       - name: Register Model
         if: success()
         run: |
-          # Ensure this path matches exactly where your python script saves the file
-          az ml model create --name "fnol-risk-model" \
+            # Register the model with explicit workspace context
+            az ml model create --name "fnol-risk-model" \
             --path "azureml://jobs/${{ env.RUN_ID }}/outputs/artifacts/outputs/fnol_model.pkl" \
-            --type "custom_model"
-
-
-            azureml:azureml_goofy_match_qy3kql7s6m_input_data_claims_data:1
-
-            
+            --type "custom_model" \
+            --resource-group "$rg_name" \
+            --workspace-name "$ml_workspace"            
