added traing data upload, model training config+model training script + metrics check + model upload to model registry

diff --git a/.github/workflows/app-dev.yml b/.github/workflows/app-dev.yml
--- a/.github/workflows/app-dev.yml
+++ b/.github/workflows/app-dev.yml
@@ -119,4 +119,43 @@ jobs:
           # if master notes a change in the sha, it replaces the old pod with a new one 
           # running the image with the new sha
           kubectl set image deployment/fnol-score-deployment fnol-score-container=$ACR_NAME.azurecr.io/fnol-score:${{ github.sha }}
-      
+      ###############################################################################################################################
+      # upload training data + model training + metrics check + push model 'fnol_model.pkl' to registry
+      ###############################################################################################################################
+      - name: Upload Training Data to Blob
+        run: |
+          st_name=$(az deployment sub show --name deploy-dev-infra --query "properties.outputs.storageAccountName.value" -o tsv)
+          container_name=$(az deployment sub show --name deploy-dev-infra --query "properties.outputs.containerName.value" -o tsv)
+          
+          az storage blob upload \
+            --account-name $st_name \
+            --container-name $container_name \
+            --file app/data/fnol_training_dataset.parquet \
+            --name paths/fnol_training_dataset.parquet \
+            --auth-mode login
+
+      - name: Run Training Job
+        id: train_job
+        run: |
+                # Run the job and capture the Run ID
+                run_id=$(az ml job create --file ./iac/ml-jobs/fnol_model_trainer_config.yml --query name -o tsv)
+                echo "RUN_ID=$run_id" >> $GITHUB_ENV
+
+      - name: Evaluate Metrics
+        run: |
+          r2_adj=$(az ml job list-metrics --name ${{ env.RUN_ID }} --query "r2_adj[-1].value" -o tsv)
+          echo "Extracted R2_ADJ: $r2_adj"
+          
+          # We want to exit if the condition (score < 0.99) is TRUE (equals 1)
+          if [ "$(echo "$r2_adj < 0.99" | bc -l)" -eq 1 ]; then
+            echo "Validation Failed: R2_ADJ is too low ($r2_adj)"
+            exit 1
+          fi
+
+      - name: Register Model
+        if: success()
+        run: |
+          # Ensure this path matches exactly where your python script saves the file
+          az ml model create --name "fnol-risk-model" \
+            --path "azureml://jobs/${{ env.RUN_ID }}/outputs/artifacts/outputs/fnol_model.pkl" \
+            --type "custom_model"
